version: '3.8'
services:
  server:
    container_name: node-server
    hostname: node-server
    build: 
      context: ./
      dockerfile: ./server.dockerfile
    depends_on:
      db:
        condition: service_healthy
    env_file: 
      - ./.env
    ports:
      - "8000:8000"    #0:0:0:0:8000と同じ.ホストの持つ全てのイーサネットのアドレスで8000ポートを開放
    command: >
     sh -c "npx drizzle-kit migrate && sleep 5 && node bundle.js" 
    networks:
      - db-server
      - web-server
  db:
    container_name: mysql-db
    image: mysql:8.0
    hostname: mysql-db
    env_file:
      - ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    ports:
      - "3309:3306"
    healthcheck: 
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 5s
      timeout: 10s
      retries: 5
    networks:
      - db-server
  web:
    container_name: next-web
    image: next:latest
    hostname: next-web
    build: 
      context: ./
      dockerfile: ./client.dev.dockerfile
      args:
        - NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
    depends_on:
      - server
    env_file: 
      - ./.env
    ports:
      - "3000:3000"
    networks:
      - web-server  
networks:
  db-server:
    driver: bridge 
  web-server:
    driver: bridge
    